apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noryx-ce

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - keycloak.yaml
  - minio.yaml
  - noryx-api-rbac.yaml
  - noryx-api.yaml
  - noryx-api-ingressroute.yaml
