apiVersion: apps/v1
kind: Deployment
metadata:
  name: noryx-backend
  namespace: noryx-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noryx-backend
  template:
    metadata:
      labels:
        app: noryx-backend
    spec:
      serviceAccountName: noryx-backend
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: noryx-backend
          image: harbor.lan/noryx-ce/noryx-backend:0.5.70-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NORYX_LISTEN_ADDR
              value: ":8080"
            - name: NORYX_BACKEND_VERSION
              value: "0.5.70"
            - name: NORYX_STORE_BACKEND
              value: "postgres"
            - name: NORYX_DATABASE_HOST
              value: "postgres"
            - name: NORYX_DATABASE_PORT
              value: "5432"
            - name: NORYX_DATABASE_NAME
              value: "noryx"
            - name: NORYX_DATABASE_USER
              value: "noryx"
            - name: NORYX_DATABASE_SSLMODE
              value: "disable"
            - name: NORYX_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: noryx-secrets
                  key: POSTGRES_PASSWORD
            - name: NORYX_ENABLE_K8S_RUNTIME
              value: "true"
            - name: NORYX_AUTH_MODE
              value: "oidc"
            - name: NORYX_OIDC_ISSUER_URL
              value: "https://datalab.noryxlab.ai/auth/realms/noryx"
            - name: NORYX_OIDC_JWKS_URL
              value: "http://keycloak:8080/auth/realms/noryx/protocol/openid-connect/certs"
            - name: NORYX_OIDC_AUDIENCE
              value: "noryx-api"
            - name: NORYX_BOOTSTRAP_ADMIN_USER
              value: "stef"
            - name: NORYX_KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NORYX_WORKLOAD_NAMESPACE
              value: "noryx-loads"
            - name: NORYX_REGISTRY_PULL_SECRET
              value: "harbor-regcred"
            - name: NORYX_REGISTRY_PUSH_SECRET
              value: "harbor-regcred"
            - name: NORYX_KEYCLOAK_BASE_URL
              value: "http://keycloak:8080/auth"
            - name: NORYX_KEYCLOAK_REALM
              value: "noryx"
            - name: NORYX_KEYCLOAK_ADMIN_REALM
              value: "master"
            - name: NORYX_KEYCLOAK_ADMIN_USER
              value: "admin"
            - name: NORYX_KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: noryx-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: NORYX_SECRETS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: noryx-secrets
                  key: NORYX_SECRETS_MASTER_KEY
            - name: NORYX_MINIO_ENDPOINT
              value: "minio.noryx-ce.svc.cluster.local:9000"
            - name: NORYX_MINIO_ACCESS_KEY
              value: "noryx"
            - name: NORYX_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: noryx-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: NORYX_MINIO_USE_SSL
              value: "false"
            - name: NORYX_MINIO_REGION
              value: "us-east-1"
            - name: NORYX_WORKSPACE_JUPYTER_IMAGE
              value: "harbor.lan/noryx-environments/noryx-python:0.2.2"
            - name: NORYX_WORKSPACE_VSCODE_IMAGE
              value: "harbor.lan/noryx-environments/noryx-python:0.2.2"
            - name: NORYX_WORKSPACE_CPU
              value: "500m"
            - name: NORYX_WORKSPACE_MEMORY
              value: "512Mi"
            - name: NORYX_WORKSPACE_EPHEMERAL_STORAGE_REQUEST
              value: "1Gi"
            - name: NORYX_WORKSPACE_EPHEMERAL_STORAGE_LIMIT
              value: "4Gi"
            - name: NORYX_WORKSPACE_PVC_ENABLED
              value: "true"
            - name: NORYX_WORKSPACE_PVC_STORAGE_CLASS
              value: "longhorn"
            - name: NORYX_WORKSPACE_PVC_SIZE
              value: "10Gi"
            - name: NORYX_WORKSPACE_PVC_ACCESS_MODE
              value: "ReadWriteMany"
            - name: NORYX_WORKSPACE_PVC_MOUNT_PATH
              value: "/mnt"
            - name: NORYX_WORKSPACE_PROFILE_PVC_ENABLED
              value: "true"
            - name: NORYX_WORKSPACE_PROFILE_PVC_STORAGE_CLASS
              value: "longhorn"
            - name: NORYX_WORKSPACE_PROFILE_PVC_SIZE
              value: "5Gi"
            - name: NORYX_WORKSPACE_PROFILE_PVC_ACCESS_MODE
              value: "ReadWriteMany"
            - name: NORYX_WORKSPACE_PROFILE_PVC_MOUNT_PATH
              value: "/home/noryx/.noryx-profile"
---
apiVersion: v1
kind: Service
metadata:
  name: noryx-backend
  namespace: noryx-ce
spec:
  selector:
    app: noryx-backend
  ports:
    - port: 8080
      targetPort: 8080
