apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: noryx-https-redirect
  namespace: noryx-ce
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: noryx-security-headers
  namespace: noryx-ce
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: noryx-http-redirect
  namespace: noryx-ce
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`datalab.noryxlab.ai`)
      kind: Rule
      middlewares:
        - name: noryx-https-redirect
      services:
        - name: noryx-frontend
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: noryx-back
  namespace: noryx-ce
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`datalab.noryxlab.ai`) && PathPrefix(`/auth`)
      kind: Rule
      middlewares:
        - name: noryx-security-headers
      services:
        - name: keycloak
          port: 8080
    - match: Host(`datalab.noryxlab.ai`) && (PathPrefix(`/api`) || PathPrefix(`/swagger`) || PathPrefix(`/workspaces`) || Path(`/healthz`))
      kind: Rule
      middlewares:
        - name: noryx-security-headers
      services:
        - name: noryx-back
          port: 8080
    - match: Host(`datalab.noryxlab.ai`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: noryx-security-headers
      services:
        - name: noryx-frontend
          port: 80
  tls:
    certResolver: le
