apiVersion: apps/v1
kind: Deployment
metadata:
  name: noryx-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noryx-back
  template:
    metadata:
      labels:
        app: noryx-back
    spec:
      serviceAccountName: noryx-back
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: noryx-back
          image: harbor.lan/noryx-ce/noryx-api:0.5.7-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NORYX_LISTEN_ADDR
              value: ":8080"
            - name: NORYX_ENABLE_K8S_RUNTIME
              value: "true"
            - name: NORYX_AUTH_MODE
              value: "oidc"
            - name: NORYX_OIDC_ISSUER_URL
              value: "https://datalab.noryxlab.ai/auth/realms/noryx"
            - name: NORYX_OIDC_JWKS_URL
              value: "http://keycloak:8080/auth/realms/noryx/protocol/openid-connect/certs"
            - name: NORYX_OIDC_AUDIENCE
              value: "noryx-api"
            - name: NORYX_BOOTSTRAP_ADMIN_USER
              value: "stef"
            - name: NORYX_KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NORYX_WORKLOAD_NAMESPACE
              value: "noryx-loads"
            - name: NORYX_REGISTRY_PULL_SECRET
              value: "harbor-regcred"
            - name: NORYX_REGISTRY_PUSH_SECRET
              value: "harbor-regcred"
            - name: NORYX_KEYCLOAK_BASE_URL
              value: "http://keycloak:8080/auth"
            - name: NORYX_KEYCLOAK_REALM
              value: "noryx"
            - name: NORYX_KEYCLOAK_ADMIN_REALM
              value: "master"
            - name: NORYX_KEYCLOAK_ADMIN_USER
              value: "admin"
            - name: NORYX_KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: noryx-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: NORYX_WORKSPACE_JUPYTER_IMAGE
              value: "harbor.lan/noryx-ce/noryx-workspace-jupyter:0.1.0"
            - name: NORYX_WORKSPACE_CPU
              value: "500m"
            - name: NORYX_WORKSPACE_MEMORY
              value: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: noryx-back
spec:
  selector:
    app: noryx-back
  ports:
    - port: 8080
      targetPort: 8080
