apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-workloads-default-deny
  namespace: noryx-loads
spec:
  podSelector:
    matchLabels:
      noryx.io/network-isolation: user-workload
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-workloads-allow-noryx-proxy
  namespace: noryx-loads
spec:
  podSelector:
    matchLabels:
      noryx.io/network-isolation: user-workload
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: noryx-ce
          podSelector:
            matchLabels:
              app: noryx-backend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-workloads-allow-dns
  namespace: noryx-loads
spec:
  podSelector:
    matchLabels:
      noryx.io/network-isolation: user-workload
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-workloads-allow-public-egress
  namespace: noryx-loads
spec:
  podSelector:
    matchLabels:
      noryx.io/network-isolation: user-workload
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 100.64.0.0/10
              - 169.254.0.0/16
              - 172.16.0.0/12
              - 192.168.0.0/16
