apiVersion: v1
kind: Secret
metadata:
  name: noryx-secrets
  namespace: noryx-ce
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me"
  KEYCLOAK_ADMIN_PASSWORD: "change-me"
  MINIO_ROOT_PASSWORD: "change-me-minio"
  NORYX_SECRETS_MASTER_KEY: "change-me-noryx-master-key"
