---
- name: Check if helm is installed
  ansible.builtin.command: helm version --short
  register: helm_version
  failed_when: false
  changed_when: false

- name: Install helm
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
  when: helm_version.rc != 0
