---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - apt-transport-https
      - python3-pip
      - open-iscsi
      - nfs-common
    state: present
    update_cache: true
