#!/usr/bin/env python3
"""
Copies the system environments' Dockerfiles into the backend, as Go source.

The environment screen reads these from GitHub when somebody opens it. That
works on an installation with an outbound route and nowhere else: on an
air-gapped platform - which is what a customer buys this for - the screen
answers "dockerfile fetch failed" for the platform's own environments, whose
content the platform was literally built from.

Embedding them makes the screen work everywhere, and makes it show what this
build contains rather than what the repository's default branch contains today,
which are two different things the moment a release is a week old.

    python3 scripts/ops/embed-system-dockerfiles.py [--check]

--check writes nothing and fails when the embedded copy has drifted from the
source. That is what CI runs, so a Dockerfile edited without regenerating is a
red build rather than a screen quietly showing last month's file.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "backend/internal/http/handlers/system_dockerfiles.go"

# Keyed by the path the environment definitions name, so the handler looks up
# exactly what it already holds.
SOURCES = [
    "environments/noryx-jupyter/Dockerfile",
    "environments/noryx-vscode/Dockerfile",
    "environments/noryx-rstudio/Dockerfile",
    "environments/noryx-python/Dockerfile",
]

HEADER = '''package handlers

// Generated by scripts/ops/embed-system-dockerfiles.py. Do not edit.
//
// The Dockerfiles of the platform's own environments, as they were when this
// binary was built. The environment screen shows these rather than fetching
// them from a repository it may have no route to - and rather than showing a
// branch that has moved on since this release.

var systemDockerfiles = map[string]string{
'''


def rendered():
    blocks = [HEADER]
    for source in SOURCES:
        content = (ROOT / source).read_text()
        # A Go raw string cannot contain a backtick; none of these do, and the
        # check keeps it that way rather than producing a file that will not
        # compile.
        if "`" in content:
            raise SystemExit(f"{source} contains a backtick, which a raw string cannot hold")
        blocks.append(f'\t"{source}": `{content}`,\n')
    blocks.append("}\n")
    return "".join(blocks)


def main():
    generated = rendered()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != generated:
            print("  the embedded system Dockerfiles have drifted from environments/")
            print("  run scripts/ops/embed-system-dockerfiles.py")
            return 1
        print(f"  the {len(SOURCES)} embedded system Dockerfiles match environments/")
        return 0
    TARGET.write_text(generated)
    print(f"  embedded {len(SOURCES)} system Dockerfiles into {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
