package http

import (
	"net/http"

	"github.com/Noryxlab/NoryxLab-CE/backend/internal/config"
	"github.com/Noryxlab/NoryxLab-CE/backend/internal/http/handlers"
)

func NewServer(cfg config.Config, h handlers.Handlers) *http.Server {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /", GetHome)
	mux.HandleFunc("GET /healthz", h.GetHealth)
	mux.HandleFunc("GET /api/v1/version", h.GetVersion)
	mux.HandleFunc("GET /api/v1/platform/overview", h.GetPlatformOverview)
	mux.HandleFunc("GET /api/v1/hardware-tiers", h.GetHardwareTiers)
	mux.HandleFunc("GET /api/v1/user/preferences", h.GetUserPreferences)
	mux.HandleFunc("GET /api/v1/organizations", h.ListAvailableOrganizations)
	mux.HandleFunc("PUT /api/v1/user/preferences", h.UpdateUserPreferences)
	mux.HandleFunc("GET /api/v1/projects", h.ListProjects)
	mux.HandleFunc("POST /api/v1/projects", h.CreateProject)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}", h.UpdateProjectMetadata)
	mux.HandleFunc("DELETE /api/v1/projects/{projectID}", h.DeleteProject)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}/ownership", h.UpdateProjectOwner)
	mux.HandleFunc("GET /api/v1/projects/{projectID}/files", h.ProxyProjectFiles)
	mux.HandleFunc("POST /api/v1/projects/{projectID}/folders", h.ProxyProjectFiles)
	mux.HandleFunc("GET /api/v1/projects/{projectID}/files/{path...}", h.ProxyProjectFiles)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}/files/{path...}", h.ProxyProjectFiles)
	mux.HandleFunc("DELETE /api/v1/projects/{projectID}/files/{path...}", h.ProxyProjectFiles)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}/members/{userID}/role", h.SetProjectMemberRole)
	mux.HandleFunc("POST /api/v1/projects/{projectID}/invitations", h.InviteProjectMember)
	mux.HandleFunc("GET /api/v1/builds", h.ListBuilds)
	mux.HandleFunc("POST /api/v1/builds", h.CreateBuild)
	mux.HandleFunc("DELETE /api/v1/builds/{buildID}", h.DeleteBuild)
	mux.HandleFunc("GET /api/v1/apps", h.ListApps)
	mux.HandleFunc("POST /api/v1/apps", h.CreateApp)
	mux.HandleFunc("GET /api/v1/apps/{appID}/logs", h.GetAppLogs)
	mux.HandleFunc("GET /api/v1/apps/{appID}/usage", h.GetAppUsage)
	mux.HandleFunc("POST /api/v1/apps/{appID}/publish", h.PublishApp)
	mux.HandleFunc("GET /api/v1/apps/{appID}/revisions", h.ListAppRevisions)
	mux.HandleFunc("POST /api/v1/apps/{appID}/revisions/{revisionID}/rollback", h.RollbackAppRevision)
	mux.HandleFunc("POST /api/v1/apps/{appID}/restart", h.RestartApp)
	mux.HandleFunc("POST /api/v1/apps/{appID}/stop", h.StopApp)
	mux.HandleFunc("DELETE /api/v1/apps/{appID}", h.DeleteApp)
	mux.HandleFunc("GET /api/v1/production/apps", h.ListProductionApps)
	mux.HandleFunc("GET /api/v1/dashboards", h.ListDashboards)
	mux.HandleFunc("POST /api/v1/dashboards", h.CreateDashboard)
	mux.HandleFunc("DELETE /api/v1/dashboards/{dashboardID}", h.DeleteDashboard)
	mux.HandleFunc("GET /api/v1/builds/{buildID}/dockerfile", h.GetBuildDockerfile)
	mux.HandleFunc("GET /api/v1/environments", h.ListEnvironments)
	mux.HandleFunc("DELETE /api/v1/environments/{environmentID}", h.DeleteEnvironment)
	mux.HandleFunc("GET /api/v1/pods", h.ListPods)
	mux.HandleFunc("POST /api/v1/pods", h.LaunchPod)
	mux.HandleFunc("GET /api/v1/workspaces", h.ListWorkspaces)
	mux.HandleFunc("POST /api/v1/workspaces", h.CreateWorkspace)
	mux.HandleFunc("DELETE /api/v1/workspaces/{workspaceID}", h.DeleteWorkspace)
	mux.HandleFunc("GET /api/v1/jobs", h.ListJobs)
	mux.HandleFunc("POST /api/v1/jobs", h.CreateJob)
	mux.HandleFunc("GET /api/v1/jobs/{jobID}/logs", h.GetJobLogs)
	mux.HandleFunc("DELETE /api/v1/jobs/{jobID}", h.DeleteJob)
	mux.HandleFunc("GET /api/v1/cronjobs", h.ListCronJobs)
	mux.HandleFunc("POST /api/v1/cronjobs", h.CreateCronJob)
	mux.HandleFunc("DELETE /api/v1/cronjobs/{cronJobID}", h.DeleteCronJob)
	mux.HandleFunc("GET /api/v1/secrets", h.ListSecrets)
	mux.HandleFunc("POST /api/v1/secrets", h.UpsertSecret)
	mux.HandleFunc("GET /api/v1/secrets/{name}", h.GetSecret)
	mux.HandleFunc("DELETE /api/v1/secrets/{name}", h.DeleteSecret)
	mux.HandleFunc("GET /api/v1/datasets", h.ListDatasets)
	mux.HandleFunc("POST /api/v1/datasets", h.CreateDataset)
	mux.HandleFunc("PUT /api/v1/datasets/{datasetID}", h.UpdateDatasetMetadata)
	mux.HandleFunc("DELETE /api/v1/datasets/{datasetID}", h.DeleteDataset)
	mux.HandleFunc("GET /api/v1/datasets/{datasetID}/objects", h.ListDatasetObjects)
	mux.HandleFunc("POST /api/v1/datasets/{datasetID}/folders", h.CreateDatasetFolder)
	mux.HandleFunc("GET /api/v1/datasets/{datasetID}/objects/{path...}", h.GetDatasetObject)
	mux.HandleFunc("PUT /api/v1/datasets/{datasetID}/objects/{path...}", h.PutDatasetObject)
	mux.HandleFunc("DELETE /api/v1/datasets/{datasetID}/objects/{path...}", h.DeleteDatasetObject)
	mux.HandleFunc("POST /api/v1/datasets/{datasetID}/download-url", h.CreateDatasetObjectDownloadURL)
	mux.HandleFunc("POST /api/v1/datasets/{datasetID}/download", h.DownloadDatasetObjects)
	mux.HandleFunc("GET /api/v1/datasets/{datasetID}/access", h.ListDatasetAccess)
	mux.HandleFunc("PUT /api/v1/datasets/{datasetID}/ownership", h.UpdateDatasetOwner)
	mux.HandleFunc("PUT /api/v1/datasets/{datasetID}/access/{subjectType}/{subjectID}", h.SetDatasetAccess)
	mux.HandleFunc("DELETE /api/v1/datasets/{datasetID}/access/{subjectType}/{subjectID}", h.DeleteDatasetAccess)
	mux.HandleFunc("PUT /api/v1/datasets/{datasetID}/access/{userID}", h.SetDatasetAccess)
	mux.HandleFunc("DELETE /api/v1/datasets/{datasetID}/access/{userID}", h.DeleteDatasetAccess)
	mux.HandleFunc("GET /api/v1/datasources", h.ListDatasources)
	mux.HandleFunc("GET /api/v1/datasource-definitions", h.ListDatasourceDefinitions)
	mux.HandleFunc("POST /api/v1/dataservices", h.CreateDataService)
	mux.HandleFunc("POST /api/v1/datasources", h.CreateDatasource)
	mux.HandleFunc("DELETE /api/v1/datasources/{datasourceID}", h.DeleteDatasource)
	mux.HandleFunc("POST /api/v1/datasources/{datasourceID}/validate", h.ValidateDatasource)
	mux.HandleFunc("GET /api/v1/datasources/{datasourceID}/logs", h.GetDataServiceLogs)
	mux.HandleFunc("POST /api/v1/datasources/{datasourceID}/restart", h.RestartDataService)
	mux.HandleFunc("GET /api/v1/repositories", h.ListRepositories)
	mux.HandleFunc("POST /api/v1/repositories", h.CreateRepository)
	mux.HandleFunc("PUT /api/v1/repositories/{repositoryID}", h.UpdateRepository)
	mux.HandleFunc("POST /api/v1/repositories/{repositoryID}/validate", h.ValidateRepository)
	mux.HandleFunc("DELETE /api/v1/repositories/{repositoryID}", h.DeleteRepository)
	mux.HandleFunc("GET /api/v1/projects/{projectID}/datasets", h.ListProjectDatasets)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}/datasets/{datasetID}", h.AttachProjectDataset)
	mux.HandleFunc("DELETE /api/v1/projects/{projectID}/datasets/{datasetID}", h.DetachProjectDataset)
	mux.HandleFunc("GET /api/v1/projects/{projectID}/ontology", h.GetProjectOntology)
	mux.HandleFunc("POST /api/v1/projects/{projectID}/ontology/scans", h.ScanProjectOntology)
	mux.HandleFunc("GET /api/v1/projects/{projectID}/datasources", h.ListProjectDatasources)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}/datasources/{datasourceID}", h.AttachProjectDatasource)
	mux.HandleFunc("DELETE /api/v1/projects/{projectID}/datasources/{datasourceID}", h.DetachProjectDatasource)
	mux.HandleFunc("GET /api/v1/projects/{projectID}/repositories", h.ListProjectRepositories)
	mux.HandleFunc("PUT /api/v1/projects/{projectID}/repositories/{repositoryID}", h.AttachProjectRepository)
	mux.HandleFunc("DELETE /api/v1/projects/{projectID}/repositories/{repositoryID}", h.DetachProjectRepository)
	mux.HandleFunc("POST /api/v1/auth/session", h.CreateWebSession)
	mux.HandleFunc("DELETE /api/v1/auth/session", h.DeleteWebSession)
	// Workspace reverse-proxy must support all HTTP methods used by Jupyter.
	for _, method := range []string{"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"} {
		mux.HandleFunc(method+" /workspaces/{workspaceID}", h.ProxyWorkspace)
		mux.HandleFunc(method+" /workspaces/{workspaceID}/{path...}", h.ProxyWorkspace)
		mux.HandleFunc(method+" /apps/{slug}", h.ProxyApp)
		mux.HandleFunc(method+" /apps/{slug}/{path...}", h.ProxyApp)
		mux.HandleFunc(method+" /dashboards/{slug}", h.ProxyApp)
		mux.HandleFunc(method+" /dashboards/{slug}/{path...}", h.ProxyApp)
	}
	mux.HandleFunc("GET /api/v1/admin/users", h.ListUsers)
	mux.HandleFunc("GET /api/v1/admin/modules", h.GetModulesStatus)
	mux.HandleFunc("GET /api/v1/admin/audit", h.ListAuditEvents)
	mux.HandleFunc("GET /api/v1/admin/executions", h.ListAdminExecutions)
	mux.HandleFunc("DELETE /api/v1/admin/executions/{kind}/{executionID}", h.StopAdminExecution)
	mux.HandleFunc("GET /api/v1/admin/overview", h.GetAdminOverview)
	mux.HandleFunc("GET /api/v1/admin/inventory", h.GetAdminInventory)
	mux.HandleFunc("GET /api/v1/admin/organizations", h.ListOrganizations)
	mux.HandleFunc("POST /api/v1/admin/organizations", h.CreateOrganization)
	mux.HandleFunc("DELETE /api/v1/admin/organizations/{organizationID}", h.DeleteOrganization)
	mux.HandleFunc("GET /api/v1/admin/organizations/{organizationID}/members", h.ListOrganizationMembers)
	mux.HandleFunc("PUT /api/v1/admin/organizations/{organizationID}/members/{userID}", h.AddOrganizationMember)
	mux.HandleFunc("DELETE /api/v1/admin/organizations/{organizationID}/members/{userID}", h.RemoveOrganizationMember)
	mux.HandleFunc("GET /api/v1/admin/audit.csv", h.ExportAuditCSV)

	mux.HandleFunc("GET /swagger", GetSwaggerUI)
	mux.HandleFunc("GET /swagger/", GetSwaggerUI)
	mux.HandleFunc("GET /swagger/openapi.yaml", GetOpenAPI)

	return &http.Server{
		Addr:    cfg.ListenAddr,
		Handler: h.AuditMutations(mux),
	}
}
